### ISSUE TITLE
Can not install package

### ISSUE THREAD

**Issue by JiaoG** [sshuair/coord-convert#1]
(base) 
When i try to install package, i have encunterd this problem. 

```
Collecting coord-convert
  Downloading https://files.pythonhosted.org/packages/59/3e/59e7165ba8ea71cd9bff77d7155f1ae2167878b0d085343fba13b4409006/coord-convert-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jj\AppData\Local\Temp\pip-install-r1ekward\coord-convert\setup.py", line 20, in <module>
        readme = f.read()
      File "C:\Users\jj\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 39: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jj\AppData\Local\Temp\pip-install-r1ekward\coord-convert\

```

Thank you for your help!

**Comment by sshuair** [comment]
重新构建了whl文件，你再试试看？

**Comment by JiaoG** [comment]
看起来还是有error

Collecting coord-convert
  Downloading https://files.pythonhosted.org/packages/3e/a5/22277402cfa110f1ef593050302aa42f405239a3b2c8c6bd61d9d1a80c4d/coord_convert-0.2-py3-none-any.whl
Collecting fiona (from coord-convert)
  Downloading https://files.pythonhosted.org/packages/3a/16/84960540e9fce61d767fd2f0f1d95f4c63e99ab5d8fddc308e8b51b059b8/Fiona-1.8.4.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 2.6MB/s
    Complete output from command python setup.py egg_info:
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\gj\AppData\Local\Temp\pip-install-mqxoic3t\fiona\

**Comment by sshuair** [comment]
你这个错误应该是gdal没装好，坐标转换这个库依赖fiona，而fiona依赖gdal去读写数据。你先检查看看gdal装好没

**Comment by JiaoG** [comment]
对  是gdal这一步出了问题  安装gdal需要安装 Microsoft Visual C++ 14.0

**Comment by sshuair** [comment]
那就先装vc++呗
