### ISSUE TITLE
3857-4362

### ISSUE THREAD

**Issue by xiefei-ok** [sshuair/coord-convert#4]
有没有什么方法是能实现web墨卡托3857和4362这两个坐标系的互相转换呢

**Comment by sshuair** [comment]
用GDAL或者QGIS可以进行坐标转换

**Comment by xiefei-ok** [comment]
-哈哈用软件我都没问题，想用代码实现



在 2021-01-08 18:52:24，"sshuair" <notifications@github.com> 写道：

用GDAL或者QGIS可以进行坐标转换

**Comment by guyanf** [comment]
https://github.com/pyproj4/pyproj/blob/master/test/test_transformer.py



在 2021/1/8 下午7:20, 谢飞 写道:
