### ISSUE TITLE
影像的转换

### ISSUE THREAD

**Issue by guyanf** [sshuair/coord-convert#5]
使用程序可以进行单点的坐标转换。
大家是如何进行影像的转换的呢？
取4角点坐标，然后仿射变化，实现纠正？
反之都有黑边的情况。

想问大家是如何转换的，谢谢！

**Comment by sshuair** [comment]
影像没法转换，只能像你说的偏移四个角点的坐标

**Comment by sshuair** [comment]
@guyanf 因本问题与本项目不相关，Issue关闭了。
